[2025-01-04T16:49:00.032+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-04T16:49:00.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.def0 manual__2025-01-04T16:48:59.874311+00:00 [queued]>
[2025-01-04T16:49:00.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.def0 manual__2025-01-04T16:48:59.874311+00:00 [queued]>
[2025-01-04T16:49:00.059+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-01-04T16:49:00.065+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): def0> on 2025-01-04 16:48:59.874311+00:00
[2025-01-04T16:49:00.069+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'def0', 'manual__2025-01-04T16:48:59.874311+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp9v3o3_ys']
[2025-01-04T16:49:00.072+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-04T16:49:00.072+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask def0
[2025-01-04T16:49:00.072+0000] {standard_task_runner.py:63} INFO - Started process 206 to run task
[2025-01-04T16:49:00.102+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.def0 manual__2025-01-04T16:48:59.874311+00:00 [running]> on host 06f70be63199
[2025-01-04T16:49:00.149+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nmashtakov' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='def0' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T16:48:59.874311+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T16:48:59.874311+00:00'
[2025-01-04T16:49:00.150+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-04T16:49:00.158+0000] {logging_mixin.py:188} INFO - Hello World
[2025-01-04T16:49:00.158+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-01-04T16:49:00.158+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-04T16:49:00.165+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=def0, run_id=manual__2025-01-04T16:48:59.874311+00:00, execution_date=20250104T164859, start_date=20250104T164900, end_date=20250104T164900
[2025-01-04T16:49:00.215+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-04T16:49:00.226+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-04T16:49:00.227+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
